global:
  scrape_interval: 10s
scrape_configs:
 - job_name: prometheus
   static_configs:
    - targets:
       - prometheus:9090
 - job_name: flask-app
   static_configs:
    - targets:
       - 15.206.92.37:8080
 - job_name: node
   static_configs:
    - targets:
       - 15.206.92.37:9100
